import UserProfile from '@/components/UserProfile';
import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [showText, setShowText] = useState(false);
  return (
    <>
      <Head>
        <title>Testing Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <button>Click Me</button>
        <div>
          <label htmlFor="randomText">Enter Random Text: </label>
          <input type="text" id="randomText" />
        </div>
        <div>
          <label htmlFor="specificText">Enter Some Specific Text: </label>
          <input type="text" id="specificText" />
        </div>
        <div>
          <input value="hello" onChange={(e) => console.log(e.target.value)} />
        </div>
        <div>
          {showText && <span>Testing Text</span>}
          <button
            onClick={() =>
              setTimeout(() => {
                setShowText((text) => !text);
              }, 1000)
            }
          >
            Show Text
          </button>
        </div>

        <UserProfile
          displayName="John Doe"
          emailAddress="johndoe@gmail.com"
          username="johndoe"
          isEmailVerified={true}
        />
      </main>
    </>
  );
}
