import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Testing Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <button>Click Me</button>
        <div>
          <label htmlFor="randomText">Enter Random Text: </label>
          <input type="text" id="randomText" />
        </div>
        <div>
          <label htmlFor="specificText">Enter Some Specific Text: </label>
          <input type="text" id="specificText" />
        </div>
      </main>
    </>
  );
}
